unique_name: Product_Code
object_type: dimension
label: Product Code
hierarchies:
  - unique_name: Product_Code_Hierarchy
    label: Product Code Hierarchy
    levels:
      - unique_name: Product_Code_Level
is_degenerate: true
level_attributes:
  - unique_name: Product_Code_Level
    label: Product Code Level
    contains_unique_names: false
    dataset: FCT_WARRANTY_CASES
    key_columns:
      - PRODUCT_CODE
    name_column: PRODUCT_CODE
type: standard
