unique_name: services
object_type: model
label: services
dimensions: []
metrics:
  - unique_name: m_FCT_SERVICES_SERVICE_ID_count
    folder: Measures
relationships:
  - unique_name: >-
      FCT_SERVICES_SERVICE_PRODUCT_CATEGORY_FK_to_PRODUCT_CATEGORY_dimension_DIM_SERVICE_PRODUCT_CATEGORY_Level
    from:
      dataset: FCT_SERVICES
      join_columns:
        - SERVICE_PRODUCT_CATEGORY_FK
    to:
      dimension: PRODUCT_CATEGORY_dimension
      level: DIM_SERVICE_PRODUCT_CATEGORY_Level
