unique_name: Services
object_type: model
label: Services
dimensions: []
metrics:
  - unique_name: m_orders_count
    folder: Measures
  - unique_name: m_item_count
    folder: Measures
  - unique_name: m_services_count
    folder: Measures
relationships:
  - unique_name: FCT_SERVICE_ORDERS_SHOP_FK_to_DIM_SHOPS_dimension_DIM_SHOPS_shop_type
    from:
      dataset: FCT_SERVICE_ORDERS
      join_columns:
        - SHOP_FK
    to:
      dimension: DIM_SHOPS_dimension
      level: DIM_SHOPS_shop_id
  - unique_name: FCT_SERVICE_ORDERS_CUSTOMER_FK_to_DIM_CUSTOMERS_dimension_DIM_CUSTOMERS_id
    from:
      dataset: FCT_SERVICE_ORDERS
      join_columns:
        - CUSTOMER_FK
    to:
      dimension: DIM_CUSTOMERS_dimension
      level: DIM_CUSTOMERS_id
  - unique_name: FCT_SERVICE_ORDERS_MARKET_FK_to_DIM_MARKETS_dimension_DIM_MARKETS_id
    from:
      dataset: FCT_SERVICE_ORDERS
      join_columns:
        - MARKET_FK
    to:
      dimension: DIM_MARKETS_dimension
      level: DIM_MARKETS_id
  - unique_name: >-
      FCT_SERVICE_ORDERS_BUSINESS_UNIT_FK_to_DIM_BUSINESS_UNITS_dimension_DIM_BUSINESS_UNITS_id
    from:
      dataset: FCT_SERVICE_ORDERS
      join_columns:
        - BUSINESS_UNIT_FK
    to:
      dimension: DIM_BUSINESS_UNITS_dimension
      level: DIM_BUSINESS_UNITS_id
  - unique_name: >-
      FCT_SERVICE_ORDERS_ORDER_CREATED_BY_EMPLOYEE_FK_to_DIM_EMPLOYEES_dimension_DIM_EMPLOYEES_name
    from:
      dataset: FCT_SERVICE_ORDERS
      join_columns:
        - ORDER_CREATED_BY_EMPLOYEE_FK
    to:
      dimension: DIM_EMPLOYEES_dimension
      level: DIM_EMPLOYEES_id
  - unique_name: FCT_SERVICE_ORDERS_ORDER_DATE_ID_to_DIM_DATES_dimension_DIM_DATES_id
    from:
      dataset: FCT_SERVICE_ORDERS
      join_columns:
        - ORDER_DATE_ID
    to:
      dimension: DIM_DATES_dimension
      level: DIM_DATES_id
  - unique_name: >-
      FCT_SERVICE_ORDERS_ORDER_PK_to_MAPPING_SERVICES_FACTS_MAPPING_SERVICES_FACTS_order_id
    from:
      dataset: FCT_SERVICE_ORDERS
      join_columns:
        - ORDER_PK
    to:
      dimension: MAPPING_SERVICES_FACTS
      level: MAPPING_SERVICES_FACTS_order_id
  - unique_name: >-
      FCT_SERVICE_ITEMS_ITEM_PK_to_MAPPING_SERVICES_FACTS_MAPPING_SERVICES_FACTS_item_id
    from:
      dataset: FCT_SERVICE_ITEMS
      join_columns:
        - ITEM_PK
    to:
      dimension: MAPPING_SERVICES_FACTS
      level: MAPPING_SERVICES_FACTS_item_id
  - unique_name: >-
      FCT_SERVICES_SERVICE_ITEM_PK_to_MAPPING_SERVICES_FACTS_MAPPING_SERVICES_FACTS_service_id
    from:
      dataset: FCT_SERVICES
      join_columns:
        - SERVICE_ITEM_PK
    to:
      dimension: MAPPING_SERVICES_FACTS
      level: MAPPING_SERVICES_FACTS_service_id
  - unique_name: >-
      FCT_SERVICES_LOCATION_FK_to_DIM_SERVICE_LOCATIONS_HIST_dimension_DIM_SERVICE_LOCATIONS_HIST_id
    from:
      dataset: FCT_SERVICES
      join_columns:
        - LOCATION_FK
    to:
      dimension: DIM_SERVICE_LOCATIONS_HIST_dimension
      level: DIM_SERVICE_LOCATIONS_HIST_id
